# Generated by Django 5.2.6 on 2025-10-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
