# Generated by Django 5.2.6 on 2025-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_savingsgoal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_savings_goal',
            field=models.BooleanField(default=False),
        ),
    ]
