# Generated by Django 5.2.6 on 2025-11-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_is_savings_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.savingsgoal'),
        ),
    ]
