# Generated by Django 5.2.6 on 2025-11-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_savings_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_savings_goal',
        ),
    ]
