# Generated by Django 5.2.6 on 2025-11-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_transaction_is_savings_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='api.category'),
        ),
    ]
