# Generated by Django 5.2.6 on 2025-11-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
    ]
